"""Standalone Python code generation for the Brainfuck runtime."""

from __future__ import annotations

import brainfuck as runtime


def compile_to_python(
    sourcecode: str, *, mode: str = "unlimited", cell_mode: str | None = None,
    cell_bits: int | str | None = None, tape_min: int | str | None = None,
    tape_max: int | str | None = None, pointer_bounds: str | None = None,
    eof_mode: str | None = None, output_mode: str | None = None, max_steps: int | None = None,
    optimize: bool = True, optimization_level: int | None = None,
) -> str:
    """Return a self-contained Python script with compiled BF operations."""
    config, level = runtime._configuration(
        mode, cell_mode, cell_bits, tape_min, tape_max, pointer_bounds, eof_mode, output_mode,
        max_steps, optimize, optimization_level,
    )
    operations = runtime._compile(
        sourcecode,
        level >= 1 and max_steps is None and config.tape_min is None and config.tape_max is None,
        level >= 1 and max_steps is None,
    )
    if level == 2 and config.cell_mode == "wrap" and max_steps is None:
        operations = runtime._optimize_clear_operations(operations)
    serialized = [(operation.kind, operation.argument, operation.step_count) for operation in operations]
    return f'''"""Generated by unlimited-brainfuck."""
import sys

SOURCE = {sourcecode!r}
CELL_MODE = {config.cell_mode!r}
CELL_BITS = {config.cell_bits!r}
TAPE_MIN = {config.tape_min!r}
TAPE_MAX = {config.tape_max!r}
POINTER_BOUNDS = {config.pointer_bounds!r}
EOF_MODE = {config.eof_mode!r}
OUTPUT_MODE = {config.output_mode!r}
MAX_STEPS = {max_steps!r}
OPTIMIZATION_LEVEL = {level!r}
OPERATIONS = {serialized!r}

tape = {{}}
pointer = instruction = steps = 0
input_stream = sys.stdin.buffer if OUTPUT_MODE == "byte" else sys.stdin
output_stream = sys.stdout.buffer if OUTPUT_MODE == "byte" else sys.stdout
while instruction < len(OPERATIONS):
    operation, argument, step_count = OPERATIONS[instruction]
    if MAX_STEPS is not None and steps + step_count > MAX_STEPS:
        raise RuntimeError(f"maximum step count {{MAX_STEPS}} reached after {{steps}} steps")
    steps += step_count
    value = tape.get(pointer, 0)
    if operation == "move":
        pointer += argument
        if (TAPE_MIN is not None and pointer < TAPE_MIN) or (TAPE_MAX is not None and pointer > TAPE_MAX):
            if POINTER_BOUNDS == "wrap":
                pointer = TAPE_MIN + (pointer - TAPE_MIN) % (TAPE_MAX - TAPE_MIN + 1)
            else:
                raise IndexError(f"pointer {{pointer}} is outside Tape range [{{TAPE_MIN}}, {{TAPE_MAX}}]")
    elif operation == "add":
        value += argument
        if CELL_MODE == "wrap":
            value %= 1 << CELL_BITS
        if value:
            tape[pointer] = value
        else:
            tape.pop(pointer, None)
    elif operation == "clear":
        tape.pop(pointer, None)
    elif operation == "output":
        output_stream.write(bytes([value & 0xFF]) if OUTPUT_MODE == "byte" else chr(value))
    elif operation == "input":
        character = input_stream.read(1)
        if character:
            value = character[0] if isinstance(character, bytes) else ord(character)
            if CELL_MODE == "wrap":
                value %= 1 << CELL_BITS
            if value:
                tape[pointer] = value
            else:
                tape.pop(pointer, None)
        elif EOF_MODE == "zero":
            tape.pop(pointer, None)
        elif EOF_MODE == "error":
            raise EOFError("input exhausted")
    elif operation == "jump_if_zero" and value == 0:
        instruction = argument
    elif operation == "jump_if_nonzero" and value != 0:
        instruction = argument
    instruction += 1
'''
